model_dir: ./saved_models  # Directory to save trained models
checkpoint_dir: ./checkpoints  # Directory to save model checkpoints
num_nodes: 171  # Number of nodes (or features) in your data
batch_size: 128  # Batchsize for training
num_epochs: 100  # Number of training epochs
learning_rate: 0.005  # Learning rate for the optimizer
input_window : 6
device: cuda:0 # Use 'cuda' for GPU or 'cpu' for CPU
dataset_name : bosbike
domain_index : True
ad_adjmat :  False
align_data: False
dropout: 0.3
feature_dim_out: 16
d_model: 32
pred_len: 1